export const formDataType = {
  ADD_STUDENT_NEW_STEP1: 'ADD_STUDENT_NEW_STEP1',
  ADD_STUDENT_NEW_STEP2: 'ADD_STUDENT_NEW_STEP2',
  ADD_STUDENT_NEW_STEP3: 'ADD_STUDENT_NEW_STEP3',
  ADD_STUDENT_NEW_STEP4: 'ADD_STUDENT_NEW_STEP4',
};